/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cabin_on_the_hill.glb --transform 
Files: cabin_on_the_hill.glb [24.92MB] > D:\projects\Threejs\r3f-vite-starter\public\models\cabin_on_the_hill-transformed.glb [1.61MB] (94%)
Author: Shahriar Shahrabi (https://sketchfab.com/shahriyarshahrabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cabin-on-the-hill-7c6de91d44e14814be0297ce58af80f2
Title: Cabin on the hill
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CabinOnTheHill(props) {
  const { nodes, materials } = useGLTF('/models/cabin_on_the_hill-transformed.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Trees_VertexColor_0.geometry} material={materials.VertexColor} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Snow_SnowWithTexture_0.geometry} material={materials.SnowWithTexture} rotation={[-Math.PI / 2, 0, 0]} />
      {/* <mesh geometry={nodes.SnowParticles_SnowParticleTexture_0.geometry} material={materials.SnowParticleTexture} rotation={[-Math.PI / 2, 0, 0]} /> */}
    </group>
  )
}

useGLTF.preload('/cabin_on_the_hill-transformed.glb')
